### ISSUE TITLE
Vue.use() typings

### ISSUE THREAD

**Issue by stefnotch** [stevethedev/vuex-tstore#3]
Adding a TStore to the Vue `this` doesn't seem to work properly.

New TStore
```typescript
import TStore from "vuex-tstore";
Vue.use(Vuex);

const store = new TStore.Store({
 // stuff
});
Vue.use(Vuex);
Vue.use(TStore);

Vue.prototype.$tstore = store;

export default store;
```

Vue Component
```javascript
this.$tstore.getters.something; // Error, $tstore is not defined
```

**Comment by stevethedev** [comment]
It took me a while to get around to looking at this issue, but I think I have a solution in place. I incorporated some of the things I usually do with my project into the library... but it should be streamlined down to just this:

```typescript
import IStoreRoot from "path/to/store/root";
declare module "vue/types/vue" {
  interface Vue {
    $tstore: IStoreRoot;
  }
}
```
I wasn't able to figure out a solution that doesn't require some kind of typedef shim, but this has worked on every project I've tried it on.
